// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nltynfkiwhpdqjtfkzjf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sdHluZmtpd2hwZHFqdGZrempmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NDk3NzEsImV4cCI6MjA2NzEyNTc3MX0.coUsI7g7s-SlAyfVzLsrlTwEQ3xqZlB8uTWQbrsyD4M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});